# Generated by Django 5.0.1 on 2024-01-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('availability', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
                ('github', models.CharField(max_length=150)),
                ('instagram', models.CharField(max_length=150)),
                ('google_location', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('about_me', models.TextField()),
                ('experience', models.IntegerField()),
                ('completed_project', models.IntegerField()),
                ('image', models.ImageField(blank=True, default='profiles/avatar.svg', null=True, upload_to='profiles')),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Tesimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='testimonial/avatar.svg', null=True, upload_to='profiles')),
                ('name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('testimonial', models.TextField()),
            ],
        ),
    ]
