# Generated by Django 5.0.1 on 2024-02-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='contact',
        ),
    ]
