# Generated by Django 5.0.1 on 2024-02-05 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_blog_blogcategory_projectcategory_servicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.blogcategory'),
            preserve_default=False,
        ),
    ]
