# Generated by Django 5.0.1 on 2024-02-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_blog_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technology',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
