# Generated by Django 5.0.1 on 2024-08-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_cvlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='skills',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
